version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12  
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - aws s3 cp build/ s3://${S3_BUCKET} --recursive
artifacts:
    files:
        - '**/*'
    base-directory: '.next'
    discard-paths: yes