import Head from "next/head";
import Layout from "../components/Layout/Default";

export default function Index() {
  return (
    <Layout>
      <Head>
        <title>Mon super blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </Layout>
  );
}
